name: Run Rust tests

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test-windows:
    name: test-windows
    runs-on: windows-latest

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-pc-windows-msvc
        default: true
        override: true
    - name: Install Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "3.9"
        directory: ${{ runner.temp }}/llvm
    - name: Set Clang environment variable
      run: echo "LIBCLANG_PATH=$PATH" >> $GITHUB_ENV
    - uses: Swatinem/rust-cache@v1
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose --workspace